config/routes.rb
Rails.application.routes.draw do
  resources :contents
  resources :areas
  resources :festivals
  resources :shrines
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  namespace :api do
    namespace :v1 do
      resources :contents do
        collection do
          get 'searchYouTube'
        end
      end
    end
  end

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/content.rb
class Content < ApplicationRecord
  extend Enumerize
  enumerize :kind, in: [:youtube, :instagram]

  has_many :content_hashtags, dependent: :destroy
  has_many :hashtags, through: :content_hashtags

  has_many :content_shrines, dependent: :destroy
  has_many :shrines, through: :content_shrines

  has_many :content_festivals, dependent: :destroy
  has_many :festivals, through: :content_festivals

  has_many :content_areas, dependent: :destroy
  has_many :areas, through: :content_areas

  before_save :make_key
  def make_key
    if self.kind == "youtube"
      self.key = self.path[32..42]
    end
  end

  after_create :make_references
  before_update :make_references

  def make_references
    content = Content.find_by(id: self.id)
    change_detail_to_hashtags(content, Shrine.all.pluck(:name))
    change_detail_to_hashtags(content, Festival.all.pluck(:name))
    change_detail_to_hashtags(content, Area.all.pluck(:name))
    make_hashtags(content)
    make_shrines(content)
    make_festivals(content)
    make_areas(content)
  end

  # 詳細からハッシュタグ抽出する
  def change_detail_to_hashtags(content, keywords)
    keywords.each do |keyword|
      idx = self.detail.index(keyword)
      next if idx.nil?
      next if idx != 0 && ['#', '＃'].include?(self.detail[idx-1])

      self.detail.insert((idx + keyword.length), ' ')
      self.detail.insert(idx, ' #')
    end
  end

  # ハッシュタグデータを生成する
  def make_hashtags(content)
    hashtags = self.detail.scan(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/)
    content.hashtags.clear
    hashtags.uniq.map do |hashtag|
      #ハッシュタグは先頭の'#'を外した上で保存
      tag = Hashtag.find_or_create_by(name: hashtag.downcase.delete('#'))
      content.hashtags << tag
    end
  end

  # ハッシュタグからShrineとのリレーションを生成する
  def make_shrines(content)
    content.shrines.clear
    content.hashtags.each do |hashtag|
      Shrine.all.each do |shrine|
        content.shrines << shrine if shrine.name== hashtag.name
      end
    end
  end

  # ハッシュタグからFestivalとのリレーションを生成する
  def make_festivals(content)
    content.festivals.clear
    content.hashtags.each do |hashtag|
      Festival.all.each do |festival|
        content.festivals << festival if festival.name== hashtag.name
      end
    end
  end

  # ハッシュタグからAreaとのリレーションを生成する
  def make_areas(content)
    content.areas.clear
    content.hashtags.each do |hashtag|
      Area.all.each do |area|
        content.areas << area if area.name == hashtag.name
      end
    end
  end

end

app/controllers/api/v1/contents_controller.rb
module Api
  module V1
    class ContentsController < ApplicationController
      # GET /contents/searchYouTube
      def searchYouTube
        q = {}
        q[:name_cont] = params[:name]
        q[:detail_cont] = params[:detail]
        q[:kind_eq] = :youtube
        @pagy, @contents = pagy(Content.ransack(q).result(distinct: true).order('created_at DESC'), items: params[:items], page: params[:page])
      end
    end
  end
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :set_content, only: %i[ show edit update destroy ]

  # GET /contents or /contents.json
  def index
    @q = Content.ransack(params[:q])
    @pagy, @contents = pagy @q.result(distinct: true).order('created_at DESC')
  end

  # GET /contents/1 or /contents/1.json
  def show
  end

  # GET /contents/new
  def new
    @content = Content.new
  end

  # GET /contents/1/edit
  def edit
  end

  # POST /contents or /contents.json
  def create
    @content = Content.new(content_params)

    respond_to do |format|
      if @content.save
        format.html { redirect_to content_url(@content), notice: "Content was successfully created." }
        format.json { render :show, status: :created, location: @content }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contents/1 or /contents/1.json
  def update
    respond_to do |format|
      if @content.update(content_params)
        format.html { redirect_to content_url(@content), notice: "Content was successfully updated." }
        format.json { render :show, status: :ok, location: @content }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contents/1 or /contents/1.json
  def destroy
    @content.destroy

    respond_to do |format|
      format.html { redirect_to contents_url, notice: "Content was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_content
      @content = Content.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def content_params
      params.require(:content).permit(:name, :kind, :path, :detail)
    end
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/views/contents/_content.html.slim
div id="#{dom_id content}"
  p
    strong = "#{Content.human_attribute_name(:name)}:"
    =< content.name
  p
    strong = "#{Content.human_attribute_name(:kind)}:"
    =< content.kind
  p
    strong = "#{Content.human_attribute_name(:path)}:"
    =< content.path
  p
    strong = "#{Content.human_attribute_name(:key)}:"
    =< content.key

  p
    strong = "#{t('labels.hashtags')}:"
    =< render_with_hashtags(@content.hashtags)

  p
    strong = "#{Content.human_attribute_name(:detail)}:"
    =< content.detail

app/views/contents/_form.html.slim
= simple_form_for(@content) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :name
    = f.input :kind
    = f.input :path
    .form-group
      label
        = t('labels.hashtags')
      .form-control
        = render_with_hashtags(@content.hashtags)
    = f.input :detail

  .form-actions
    = f.button :submit

app/views/contents/_panel_content.html.slim
.panel
	.panel-header
	.panel-body
    = content_tag 'iframe', nil, src: "https://www.youtube.com/embed/#{content.key}", \
      frameborder: 0, gesture: 'media', allow: 'encrypted-media', allowfullscreen: true
	.panel-footer
		= link_to content.name, edit_content_path(content)

app/views/contents/edit.html.slim
h1 = t('.title')

== render "form", content: @content

br

div
  => link_to t('labels.show'), @content
  '|
  =< link_to t('labels.back.index'), contents_path

app/views/contents/index.html.slim
p style="color: green" = notice

h1 = t('.title')

= search_form_for @q do |f|
  = f.input :name_cont
  = f.input :shrines_id_in, as: :select, collection: Shrine.all
  = f.input :festivals_id_in, as: :select, collection: Festival.all
  = f.input :areas_id_in, as: :select, collection: Area.all
  = f.submit

hr

#contents
  - @contents.each do |content|
    == render "panel_content", content: content

hr

= pagy_bootstrap_nav(@pagy).html_safe

= link_to t('labels.new'), new_content_path

app/views/contents/new.html.slim
h1 = t('.title')

== render "form", content: @content

br

div
  = link_to t('labels.back.index'), contents_path

app/views/contents/show.html.slim
p style="color: green" = notice

== render @content

div
  => link_to t('labels.edit'), edit_content_path(@content)
  '|
  =< link_to t('labels.back.index'), contents_path

  = button_to @content, method: :delete, form: { data: { turbo_confirm: t('messages.delete') } }
    = t('labels.delete')