config/routes.rb
Rails.application.routes.draw do
  resources :contents
  resources :areas
  resources :festivals
  resources :shrines
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  namespace :api do
    namespace :v1 do
      resources :contents do
        collection do
          get 'searchYouTube'
        end
      end
    end
  end

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/shrine.rb
class Shrine < ApplicationRecord
end

app/controllers/shrines_controller.rb
class ShrinesController < ApplicationController
  before_action :set_shrine, only: %i[ show edit update destroy ]

  # GET /shrines or /shrines.json
  def index
    @q = Shrine.ransack(params[:q])
    @pagy, @shrines = pagy @q.result(distinct: true).order('created_at DESC')
  end

  # GET /shrines/1 or /shrines/1.json
  def show
  end

  # GET /shrines/new
  def new
    @shrine = Shrine.new
  end

  # GET /shrines/1/edit
  def edit
  end

  # POST /shrines or /shrines.json
  def create
    @shrine = Shrine.new(shrine_params)

    respond_to do |format|
      if @shrine.save
        format.html { redirect_to shrine_url(@shrine), notice: "Shrine was successfully created." }
        format.json { render :show, status: :created, location: @shrine }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @shrine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shrines/1 or /shrines/1.json
  def update
    respond_to do |format|
      if @shrine.update(shrine_params)
        format.html { redirect_to shrine_url(@shrine), notice: "Shrine was successfully updated." }
        format.json { render :show, status: :ok, location: @shrine }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @shrine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shrines/1 or /shrines/1.json
  def destroy
    @shrine.destroy

    respond_to do |format|
      format.html { redirect_to shrines_url, notice: "Shrine was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shrine
      @shrine = Shrine.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def shrine_params
      params.require(:shrine).permit(:name, :address)
    end
end

app/helpers/shrines_helper.rb
module ShrinesHelper
end

app/views/shrines/_form.html.slim
= simple_form_for(@shrine) do |form|
  - if @shrine.errors.any?
    div style="color: red"
      h2 = "#{pluralize(@shrine.errors.count, "error")} prohibited this shrine from being saved:"
      ul
        - @shrine.errors.each do |error|
          li = error.full_message

  div
    = form.input :name

  div
    = form.input :address

  div
    = form.input :content

  div
    = form.submit

app/views/shrines/_shrine.html.slim
div id="#{dom_id shrine}"
  p
    strong = "#{Shrine.human_attribute_name(:name)}:"
    =< shrine.name
  p
    strong = "#{Shrine.human_attribute_name(:address)}:"
    =< shrine.address
  p
    strong = "#{Shrine.human_attribute_name(:content)}:"
    =< shrine.content

app/views/shrines/edit.html.slim
h1 = t('.title')

== render "form", shrine: @shrine

br

div
  => link_to t('labels.show'), @shrine
  '|
  =< link_to t('labels.back.index'), shrines_path

app/views/shrines/index.html.slim
p style="color: green" = notice

h1 = t('.title')

= search_form_for @q do |f|
  = f.text_field :name_cont
  = f.submit

hr

#shrines
  table
    thead
      tr
        th
          = Shrine.human_attribute_name(:name)
        th
    tbody
      - @shrines.each do |shrine|
        tr
          td
            = link_to shrine.name, edit_shrine_path(shrine)
          td
            = button_to shrine, method: :delete, form: { data: { turbo_confirm: t('messages.delete') } }
              = t('labels.delete')

hr

= pagy_bootstrap_nav(@pagy).html_safe

= link_to t('labels.new'), new_shrine_path

app/views/shrines/new.html.slim
h1 = t('.title')

== render "form", shrine: @shrine

br

div
  = link_to t('labels.back.index'), shrines_path

app/views/shrines/show.html.slim
p style="color: green" = notice

== render @shrine

div
  => link_to t('labels.edit'), edit_shrine_path(@shrine)
  '|
  =< link_to t('labels.back.index'), shrines_path

  = button_to @shrine, method: :delete, form: { data: { turbo_confirm: t('messages.delete') } }
    = t('labels.delete')