config/routes.rb
Rails.application.routes.draw do
  resources :contents
  resources :areas
  resources :festivals
  resources :shrines
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  namespace :api do
    namespace :v1 do
      resources :contents do
        collection do
          get 'searchYouTube'
        end
      end
    end
  end

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/area.rb
class Area < ApplicationRecord
  belongs_to :shrine
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  before_action :set_area, only: %i[ show edit update destroy ]

  # GET /areas or /areas.json
  def index
    @q = Area.ransack(params[:q])
    @pagy, @areas = pagy @q.result(distinct: true).order('created_at DESC')
  end

  # GET /areas/1 or /areas/1.json
  def show
  end

  # GET /areas/new
  def new
    @area = Area.new
  end

  # GET /areas/1/edit
  def edit
  end

  # POST /areas or /areas.json
  def create
    @area = Area.new(area_params)

    respond_to do |format|
      if @area.save
        format.html { redirect_to area_url(@area), notice: "Area was successfully created." }
        format.json { render :show, status: :created, location: @area }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /areas/1 or /areas/1.json
  def update
    respond_to do |format|
      if @area.update(area_params)
        format.html { redirect_to area_url(@area), notice: "Area was successfully updated." }
        format.json { render :show, status: :ok, location: @area }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /areas/1 or /areas/1.json
  def destroy
    @area.destroy

    respond_to do |format|
      format.html { redirect_to areas_url, notice: "Area was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_area
      @area = Area.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def area_params
      params.require(:area).permit(:shrine_id, :name, :address, :crest, :color, :content)
    end
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/views/areas/_area.html.slim
div id="#{dom_id area}"
  p
    strong = "#{Area.human_attribute_name(:shrine)}:"
    =< area.shrine.name
  p
    strong = "#{Area.human_attribute_name(:name)}:"
    =< area.name
  p
    strong = "#{Area.human_attribute_name(:address)}:"
    =< area.address
  p
    strong = "#{Area.human_attribute_name(:crest)}:"
    =< area.crest
  p
    strong = "#{Area.human_attribute_name(:color)}:"
    =< area.color
  p
    strong = "#{Area.human_attribute_name(:content)}:"
    =< area.content

app/views/areas/_form.html.slim
= simple_form_for(@area) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.association :shrine
    = f.input :name
    = f.input :address
    = f.input :crest
    = f.input :color
    = f.input :content

  .form-actions
    = f.button :submit

app/views/areas/edit.html.slim
h1 = t('.title')

== render "form", area: @area

br

div
  => link_to t('labels.show'), @area
  '|
  =< link_to t('labels.back.index'), areas_path

app/views/areas/index.html.slim
p style="color: green" = notice

h1 = t('.title')

= search_form_for @q do |f|
  = f.input :name_cont
  = f.input :shrine_id_eq, as: :select, collection: Shrine.all
  = f.submit

hr

#areas
  table
    thead
      tr
        th
          = Area.human_attribute_name(:shrine)
        th
          = Area.human_attribute_name(:name)
        th
    tbody
      - @areas.each do |area|
        tr
          td
            = area.shrine.name
          td
            = link_to area.name, edit_area_path(area)
          td
            = button_to area, method: :delete, form: { data: { turbo_confirm: t('messages.delete') } }
              = t('labels.delete')

hr

= pagy_bootstrap_nav(@pagy).html_safe

= link_to t('labels.new'), new_area_path

app/views/areas/new.html.slim
h1 = t('.title')

== render "form", area: @area

br

div
  = link_to t('labels.back.index'), areas_path

app/views/areas/show.html.slim
p style="color: green" = notice

== render @area

div
  => link_to t('labels.edit'), edit_area_path(@area)
  '|
  =< link_to t('labels.back.index'), areas_path

  = button_to @area, method: :delete, form: { data: { turbo_confirm: t('messages.delete') } }
    = t('labels.delete')