config/routes.rb
Rails.application.routes.draw do
  resources :contents
  resources :areas
  resources :festivals
  resources :shrines
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  namespace :api do
    namespace :v1 do
      resources :contents do
        collection do
          get 'searchYouTube'
        end
      end
    end
  end

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | FestivalDb
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
  body.container
    = render template:'layouts/header'
    = yield
    = render template:'layouts/footer'

app/views/layouts/footer.slim
footer
  .container 
    .d-flex.flex-wrap.justify-content-between.align-items-center.py-3.my-4.border-top
      .col-md-4.d-flex.align-items-center
      .col-md-4.justify-content-end.list-unstyled.d-flex
        = "© 2022 Newburu"

app/views/layouts/header.slim
header
  .container
    .d-flex.flex-wrap.justify-content-center.py-3.mb-4.border-bottom
      = link_to("/", {class: "d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none"})
        span.fs-4
          = "TITLE"
      ul.nav.nav-pills
        li.nav-item
          = link_to("Home", "#", {class: "nav-link active"})
        li.nav-item
          = link_to("Shrines", shrines_path, {class: "nav-link"})
        li.nav-item
          = link_to("Festivals", festivals_path, {class: "nav-link"})
        li.nav-item
          = link_to("Areas", areas_path, {class: "nav-link"})
        li.nav-item
          = link_to("Contents", contents_path, {class: "nav-link"})